import React, { useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
type Priority='low'|'moderate'|'high';type Patient={id:string;name:string;age:number;gender:string;date:string;time:string;visit:string;note:string;priority:Priority;prescribed:boolean};
const C={blue:'#246BFD',ink:'#152B4F',muted:'#75839A',canvas:'#FBF7F2',card:'#fff',line:'#E6EAF0',soft:'#EEF4FF',low:'#10B981',moderate:'#D97706',high:'#E5484D'};
const initial:Patient[]=[{id:'1',name:'Riya Sharma',age:34,gender:'Female',date:'Today',time:'09:00 AM',visit:'In-clinic',note:'Acute viral bronchitis with mild fever.',priority:'high',prescribed:true},{id:'2',name:'Arjun Mehta',age:52,gender:'Male',date:'Yesterday',time:'10:30 AM',visit:'Video consultation',note:'Essential hypertension, Stage 2 — review ongoing.',priority:'moderate',prescribed:false},{id:'3',name:'Suresh Kumar',age:61,gender:'Male',date:'02 Sep 2026',time:'11:15 AM',visit:'In-clinic',note:'Post-operative follow-up — healing well.',priority:'low',prescribed:true}];
export default function History(){const router=useRouter();const[tab,setTab]=useState<'patients'|'referrals'|'prescriptions'>('patients');const[priorityFor,setPriorityFor]=useState<Patient|null>(null);const[viewPrescription,setViewPrescription]=useState<Patient|null>(null);const[items,setItems]=useState(initial);const update=(id:string,patch:Partial<Patient>)=>setItems(xs=>xs.map(x=>x.id===id?{...x,...patch}:x));const prescribe=(p:Patient)=>router.push({pathname:'/(tabs2)/new',params:{patientName:p.name,patientAge:String(p.age)}} as any);
return <SafeAreaView style={s.screen} edges={['top','left','right']}><View style={s.header}><View><Text style={s.title}>History</Text><Text style={s.sub}>Your patient care records</Text></View></View><View style={s.tabs}><Tab label="Patients" active={tab==='patients'} onPress={()=>setTab('patients')}/><Tab label="Referrals" active={tab==='referrals'} onPress={()=>setTab('referrals')}/><Tab label="Prescriptions" active={tab==='prescriptions'} onPress={()=>setTab('prescriptions')}/></View>{tab==='patients'?<ScrollView contentContainerStyle={s.list}>{items.map(p=><View key={p.id} style={s.card}><View style={s.top}><View style={s.avatar}><Text style={s.avatarText}>{p.name.split(' ').map(x=>x[0]).join('')}</Text></View><View style={{flex:1}}><Text style={s.name}>{p.name}</Text><Text style={s.meta}>Age {p.age} · {p.gender} · {p.time}</Text></View><Pressable onPress={()=>setPriorityFor(p)} style={[s.priority,{backgroundColor:C[p.priority]+'18'}]}><Ionicons name="flag-outline" size={14} color={C[p.priority]}/><Text style={[s.priorityText,{color:C[p.priority]}]}>{p.priority}</Text></Pressable></View><Text style={s.info}>{p.date} · {p.visit}</Text><TextInput value={p.note} onChangeText={note=>update(p.id,{note})} style={s.note} multiline/><Pressable style={s.rx} onPress={()=>p.prescribed?setViewPrescription(p):prescribe(p)}><Ionicons name={p.prescribed?'document-text-outline':'add-circle-outline'} size={17} color={C.blue}/><Text style={s.rxText}>{p.prescribed?'Prescribed':'Prescribe'}</Text></Pressable></View>)}</ScrollView>:tab==='referrals'?<ReferralHistory/>:<PrescriptionHistory items={items} onView={setViewPrescription}/>}<Modal visible={!!priorityFor} transparent animationType="fade"><Picker title="Set priority" items={['low','moderate','high']} value={priorityFor?.priority||''} onPick={v=>{if(priorityFor)update(priorityFor.id,{priority:v as Priority});setPriorityFor(null)}}/></Modal><Modal visible={!!viewPrescription} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>setViewPrescription(null)}>{viewPrescription&&<Prescription patient={viewPrescription} onClose={()=>setViewPrescription(null)}/>}</Modal></SafeAreaView>}
function Tab({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.tab,active&&s.tabOn]}><Text style={[s.tabText,active&&s.tabTextOn]}>{label}</Text></Pressable>}
function Picker({title,items,value,onPick}:{title:string;items:string[];value:string;onPick:(x:string)=>void}){return <View style={s.overlay}><View style={s.sheet}><Text style={s.sheetTitle}>{title}</Text>{items.map(x=><Pressable key={x} onPress={()=>onPick(x)} style={s.option}><Text style={[s.optionText,value===x&&{color:C.blue}]}>{x}</Text>{value===x&&<Ionicons name="checkmark" size={18} color={C.blue}/>}</Pressable>)}</View></View>}
function ReferralHistory(){return <ScrollView contentContainerStyle={s.list}><View style={s.card}><Text style={s.name}>Referral: Neha Kapoor</Text><Text style={s.note}>Neurology review requested for recurrent severe headaches.</Text></View></ScrollView>}
function PrescriptionHistory({items,onView}:{items:Patient[];onView:(p:Patient)=>void}){return <ScrollView contentContainerStyle={s.list}>{items.filter(p=>p.prescribed).map(p=><Pressable key={p.id} style={s.card} onPress={()=>onView(p)}><View style={s.top}><View style={s.avatar}><Ionicons name="document-text-outline" size={19} color={C.blue}/></View><View style={{flex:1}}><Text style={s.name}>{p.name}</Text><Text style={s.meta}>Issued {p.date} · Tap to view</Text></View><Ionicons name="chevron-forward" size={20} color={C.muted}/></View></Pressable>)}</ScrollView>}
function Prescription({patient,onClose}:{patient:Patient;onClose:()=>void}){return <SafeAreaView style={s.prescription}><View style={s.rxHeader}><Text style={s.title}>Prescription</Text><Pressable onPress={onClose}><Ionicons name="close" size={24} color={C.ink}/></Pressable></View><View style={s.paper}><Text style={s.rxName}>{patient.name}</Text><Text style={s.meta}>Age {patient.age} · {patient.gender}</Text><Text style={s.rule}>Clinical note</Text><Text style={s.note}>{patient.note}</Text><Text style={s.rule}>Medicines</Text><Text style={s.medicine}>1. Paracetamol 650 mg — After food · 3 days</Text><Text style={s.medicine}>2. Azithromycin 500 mg — Once daily · 5 days</Text></View></SafeAreaView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.canvas},header:{padding:20},title:{fontSize:23,fontWeight:'800',color:C.ink},sub:{color:C.muted,fontSize:12,marginTop:3},tabs:{marginHorizontal:16,padding:4,borderRadius:13,flexDirection:'row',backgroundColor:C.soft},tab:{flex:1,paddingVertical:9,borderRadius:9,alignItems:'center'},tabOn:{backgroundColor:C.blue},tabText:{fontWeight:'800',fontSize:10,color:C.muted},tabTextOn:{color:'#fff'},list:{padding:16,gap:11},card:{backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:16,padding:14},top:{flexDirection:'row',alignItems:'center'},avatar:{height:36,width:36,borderRadius:12,backgroundColor:C.soft,alignItems:'center',justifyContent:'center',marginRight:9},avatarText:{fontWeight:'800',fontSize:11,color:C.blue},name:{fontSize:15,fontWeight:'800',color:C.ink},meta:{fontSize:11,marginTop:3,color:C.muted},priority:{flexDirection:'row',alignItems:'center',gap:3,padding:6,borderRadius:8},priorityText:{fontSize:10,fontWeight:'800',textTransform:'capitalize'},info:{fontSize:11,color:C.muted,marginTop:11},note:{minHeight:55,backgroundColor:'#F8FAFC',borderRadius:9,padding:10,marginTop:10,fontSize:12,lineHeight:18,color:C.ink},rx:{alignSelf:'flex-start',marginTop:11,paddingHorizontal:9,paddingVertical:7,borderRadius:9,backgroundColor:C.soft,flexDirection:'row',gap:5,alignItems:'center'},rxText:{fontSize:11,fontWeight:'800',color:C.blue},overlay:{flex:1,justifyContent:'flex-end',backgroundColor:'#0006'},sheet:{backgroundColor:C.card,borderTopLeftRadius:22,borderTopRightRadius:22,padding:20,paddingBottom:32},sheetTitle:{fontSize:17,fontWeight:'800',color:C.ink,marginBottom:7},option:{height:49,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:C.line},optionText:{flex:1,fontSize:14,fontWeight:'700',color:C.ink},prescription:{flex:1,backgroundColor:C.canvas},rxHeader:{padding:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},paper:{margin:16,padding:20,borderRadius:16,backgroundColor:C.card,borderWidth:1,borderColor:C.line},rxName:{fontSize:20,fontWeight:'800',color:C.ink},rule:{fontSize:10,fontWeight:'800',letterSpacing:1,color:C.muted,marginTop:23,marginBottom:7},medicine:{fontSize:13,color:C.ink,lineHeight:25}});
