ALTER TABLE "appointments" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "audit_logs" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "auth_sessions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "consultations" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "departments" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "diagnoses" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "diagnostic_centers" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "diagnostic_order_items" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "diagnostic_orders" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "diagnostic_reports" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "dispensing_logs" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "doctor_availability" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "doctor_profiles" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "documents" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "facilities" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "follow_ups" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "high_risk_alerts" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "medical_records" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "medicines" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "notifications" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "otp_verifications" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "patient_facility_links" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "patient_profiles" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pharmacies" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pharmacist_profiles" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pharmacy_inventory" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pharmacy_order_items" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pharmacy_orders" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "prescription_items" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "prescriptions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "queue_tokens" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "receptionist_profiles" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "referrals" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "roles" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "teleconsultation_sessions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_roles" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" DISABLE ROW LEVEL SECURITY;